version: "3"

volumes:
  work:

services:

  notebook:
    image: jupyter/all-spark-notebook:4cdbc9cdb7d1
    environment:
      - "JUPYTER_ENABLE_LAB=yes"
      - "SPARK_OPTS=--master=spark://spark-master:7077"
    ports:
      - 8888:8888
      - 4040:4040
    command: start-notebook.sh --NotebookApp.token=''
    volumes:
      - $PWD/work:/home/jovyan/work

  spark-master:
    image: bde2020/spark-master:2.4.0-hadoop2.7
    container_name: spark-master
    ports:
      - "5000:8080"
    environment:
      - INIT_DAEMON_STEP=setup_spark

  spark-worker:
    image: bde2020/spark-worker:2.4.0-hadoop2.7
    container_name: spark-worker-1
    ports:
      - "8081:8081"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
      - "spark.driver.bindAddress=0.0.0.0"
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: '0.25'
        reservations:
          cpus: '0.25'
